#!/usr/bin/env ruby
require_relative 'boot'

configuration = ROM::Configuration.new(:sql, "mysql2:///#{DB_CONFIG[:name]}", DB_CONFIG)
configuration.register_relation(Companies, Posts)
MAIN_CONTAINER = ROM.container(configuration)

Pry.start